// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c2smessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "c2smessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace c2smessage {
class c2sbasemessageDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<c2sbasemessage> {
} _c2sbasemessage_default_instance_;
class req_thirdparty_loginDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<req_thirdparty_login> {
} _req_thirdparty_login_default_instance_;

namespace protobuf_c2smessage_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(c2sbasemessage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(c2sbasemessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(c2sbasemessage, sid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(c2sbasemessage, data_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(req_thirdparty_login, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(req_thirdparty_login, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(req_thirdparty_login, unionid_),
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(c2sbasemessage)},
  { 9, 15, sizeof(req_thirdparty_login)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_c2sbasemessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_req_thirdparty_login_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "c2smessage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _c2sbasemessage_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _req_thirdparty_login_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _c2sbasemessage_default_instance_.DefaultConstruct();
  _req_thirdparty_login_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\020c2smessage.proto\022\nc2smessage\"+\n\016c2sbas"
      "emessage\022\013\n\003sid\030\001 \002(\005\022\014\n\004data\030\002 \002(\014\"\'\n\024r"
      "eq_thirdparty_login\022\017\n\007unionid\030\001 \002(\005*M\n\016"
      "c2s_message_id\022\022\n\016msg_invalid_id\020\000\022\r\n\tms"
      "g_login\020\001\022\030\n\024msg_thirdparty_login\020\002"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 195);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "c2smessage.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_c2smessage_2eproto

const ::google::protobuf::EnumDescriptor* c2s_message_id_descriptor() {
  protobuf_c2smessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c2smessage_2eproto::file_level_enum_descriptors[0];
}
bool c2s_message_id_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int c2sbasemessage::kSidFieldNumber;
const int c2sbasemessage::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

c2sbasemessage::c2sbasemessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_c2smessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:c2smessage.c2sbasemessage)
}
c2sbasemessage::c2sbasemessage(const c2sbasemessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_data()) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  sid_ = from.sid_;
  // @@protoc_insertion_point(copy_constructor:c2smessage.c2sbasemessage)
}

void c2sbasemessage::SharedCtor() {
  _cached_size_ = 0;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sid_ = 0;
}

c2sbasemessage::~c2sbasemessage() {
  // @@protoc_insertion_point(destructor:c2smessage.c2sbasemessage)
  SharedDtor();
}

void c2sbasemessage::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void c2sbasemessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* c2sbasemessage::descriptor() {
  protobuf_c2smessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c2smessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const c2sbasemessage& c2sbasemessage::default_instance() {
  protobuf_c2smessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

c2sbasemessage* c2sbasemessage::New(::google::protobuf::Arena* arena) const {
  c2sbasemessage* n = new c2sbasemessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void c2sbasemessage::Clear() {
// @@protoc_insertion_point(message_clear_start:c2smessage.c2sbasemessage)
  if (has_data()) {
    GOOGLE_DCHECK(!data_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*data_.UnsafeRawStringPointer())->clear();
  }
  sid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool c2sbasemessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:c2smessage.c2sbasemessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 sid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_sid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:c2smessage.c2sbasemessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:c2smessage.c2sbasemessage)
  return false;
#undef DO_
}

void c2sbasemessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:c2smessage.c2sbasemessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 sid = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->sid(), output);
  }

  // required bytes data = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:c2smessage.c2sbasemessage)
}

::google::protobuf::uint8* c2sbasemessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:c2smessage.c2sbasemessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 sid = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->sid(), target);
  }

  // required bytes data = 2;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:c2smessage.c2sbasemessage)
  return target;
}

size_t c2sbasemessage::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:c2smessage.c2sbasemessage)
  size_t total_size = 0;

  if (has_data()) {
    // required bytes data = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  if (has_sid()) {
    // required int32 sid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sid());
  }

  return total_size;
}
size_t c2sbasemessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:c2smessage.c2sbasemessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required bytes data = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());

    // required int32 sid = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sid());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void c2sbasemessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:c2smessage.c2sbasemessage)
  GOOGLE_DCHECK_NE(&from, this);
  const c2sbasemessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const c2sbasemessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:c2smessage.c2sbasemessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:c2smessage.c2sbasemessage)
    MergeFrom(*source);
  }
}

void c2sbasemessage::MergeFrom(const c2sbasemessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:c2smessage.c2sbasemessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_data();
      data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
    }
    if (cached_has_bits & 0x00000002u) {
      sid_ = from.sid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void c2sbasemessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:c2smessage.c2sbasemessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void c2sbasemessage::CopyFrom(const c2sbasemessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:c2smessage.c2sbasemessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool c2sbasemessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void c2sbasemessage::Swap(c2sbasemessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void c2sbasemessage::InternalSwap(c2sbasemessage* other) {
  data_.Swap(&other->data_);
  std::swap(sid_, other->sid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata c2sbasemessage::GetMetadata() const {
  protobuf_c2smessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c2smessage_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// c2sbasemessage

// required int32 sid = 1;
bool c2sbasemessage::has_sid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void c2sbasemessage::set_has_sid() {
  _has_bits_[0] |= 0x00000002u;
}
void c2sbasemessage::clear_has_sid() {
  _has_bits_[0] &= ~0x00000002u;
}
void c2sbasemessage::clear_sid() {
  sid_ = 0;
  clear_has_sid();
}
::google::protobuf::int32 c2sbasemessage::sid() const {
  // @@protoc_insertion_point(field_get:c2smessage.c2sbasemessage.sid)
  return sid_;
}
void c2sbasemessage::set_sid(::google::protobuf::int32 value) {
  set_has_sid();
  sid_ = value;
  // @@protoc_insertion_point(field_set:c2smessage.c2sbasemessage.sid)
}

// required bytes data = 2;
bool c2sbasemessage::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void c2sbasemessage::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
void c2sbasemessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
void c2sbasemessage::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
const ::std::string& c2sbasemessage::data() const {
  // @@protoc_insertion_point(field_get:c2smessage.c2sbasemessage.data)
  return data_.GetNoArena();
}
void c2sbasemessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c2smessage.c2sbasemessage.data)
}
#if LANG_CXX11
void c2sbasemessage::set_data(::std::string&& value) {
  set_has_data();
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c2smessage.c2sbasemessage.data)
}
#endif
void c2sbasemessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c2smessage.c2sbasemessage.data)
}
void c2sbasemessage::set_data(const void* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c2smessage.c2sbasemessage.data)
}
::std::string* c2sbasemessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:c2smessage.c2sbasemessage.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* c2sbasemessage::release_data() {
  // @@protoc_insertion_point(field_release:c2smessage.c2sbasemessage.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void c2sbasemessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:c2smessage.c2sbasemessage.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int req_thirdparty_login::kUnionidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

req_thirdparty_login::req_thirdparty_login()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_c2smessage_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:c2smessage.req_thirdparty_login)
}
req_thirdparty_login::req_thirdparty_login(const req_thirdparty_login& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  unionid_ = from.unionid_;
  // @@protoc_insertion_point(copy_constructor:c2smessage.req_thirdparty_login)
}

void req_thirdparty_login::SharedCtor() {
  _cached_size_ = 0;
  unionid_ = 0;
}

req_thirdparty_login::~req_thirdparty_login() {
  // @@protoc_insertion_point(destructor:c2smessage.req_thirdparty_login)
  SharedDtor();
}

void req_thirdparty_login::SharedDtor() {
}

void req_thirdparty_login::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* req_thirdparty_login::descriptor() {
  protobuf_c2smessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c2smessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const req_thirdparty_login& req_thirdparty_login::default_instance() {
  protobuf_c2smessage_2eproto::InitDefaults();
  return *internal_default_instance();
}

req_thirdparty_login* req_thirdparty_login::New(::google::protobuf::Arena* arena) const {
  req_thirdparty_login* n = new req_thirdparty_login;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void req_thirdparty_login::Clear() {
// @@protoc_insertion_point(message_clear_start:c2smessage.req_thirdparty_login)
  unionid_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool req_thirdparty_login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:c2smessage.req_thirdparty_login)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 unionid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_unionid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unionid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:c2smessage.req_thirdparty_login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:c2smessage.req_thirdparty_login)
  return false;
#undef DO_
}

void req_thirdparty_login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:c2smessage.req_thirdparty_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 unionid = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->unionid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:c2smessage.req_thirdparty_login)
}

::google::protobuf::uint8* req_thirdparty_login::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:c2smessage.req_thirdparty_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 unionid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->unionid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:c2smessage.req_thirdparty_login)
  return target;
}

size_t req_thirdparty_login::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:c2smessage.req_thirdparty_login)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required int32 unionid = 1;
  if (has_unionid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->unionid());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void req_thirdparty_login::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:c2smessage.req_thirdparty_login)
  GOOGLE_DCHECK_NE(&from, this);
  const req_thirdparty_login* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const req_thirdparty_login>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:c2smessage.req_thirdparty_login)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:c2smessage.req_thirdparty_login)
    MergeFrom(*source);
  }
}

void req_thirdparty_login::MergeFrom(const req_thirdparty_login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:c2smessage.req_thirdparty_login)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_unionid()) {
    set_unionid(from.unionid());
  }
}

void req_thirdparty_login::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:c2smessage.req_thirdparty_login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void req_thirdparty_login::CopyFrom(const req_thirdparty_login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:c2smessage.req_thirdparty_login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool req_thirdparty_login::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void req_thirdparty_login::Swap(req_thirdparty_login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void req_thirdparty_login::InternalSwap(req_thirdparty_login* other) {
  std::swap(unionid_, other->unionid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata req_thirdparty_login::GetMetadata() const {
  protobuf_c2smessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c2smessage_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// req_thirdparty_login

// required int32 unionid = 1;
bool req_thirdparty_login::has_unionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void req_thirdparty_login::set_has_unionid() {
  _has_bits_[0] |= 0x00000001u;
}
void req_thirdparty_login::clear_has_unionid() {
  _has_bits_[0] &= ~0x00000001u;
}
void req_thirdparty_login::clear_unionid() {
  unionid_ = 0;
  clear_has_unionid();
}
::google::protobuf::int32 req_thirdparty_login::unionid() const {
  // @@protoc_insertion_point(field_get:c2smessage.req_thirdparty_login.unionid)
  return unionid_;
}
void req_thirdparty_login::set_unionid(::google::protobuf::int32 value) {
  set_has_unionid();
  unionid_ = value;
  // @@protoc_insertion_point(field_set:c2smessage.req_thirdparty_login.unionid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace c2smessage

// @@protoc_insertion_point(global_scope)
